spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    url: jdbc:h2:tcp://localhost/~/maybedo
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        globally_quoted_identifiers: true
        show_sql: true
        format_sql: true
        generate_statistics: true
  mvc:
    static-path-pattern: /images/**
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


logging.level:
  org.hibernate.SQL: debug

